---

- hosts: all
  user: ubuntu
  become: true
  tasks:

  - name: Update and install apache and pip packages on Ubuntu
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: Update and install apache and pip packages on CentOS
    apt:
      name: 
      - httpd
      - php
      state: latest
      update_cache: true
    when: ansible_distribution == "CentOS"
