---

- hosts: all
  user: ubuntu
  become: true
  tasks:

  - name: Update and install apache and pip packages
    # Package is a module, that determines what package manager the system uses, and runs it.
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
      update_cache: true
