---

- hosts: all
  user: ubuntu
  become: true
  tasks:

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent

  # The block above already removes this package, so the block below will do nothing.
  - name: Remove pip package
    apt:
      name: libapache2-mod-pip
      state: absent
